apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tafbn9ai9-nodejs 
  janus-idp.io/tekton: tafbn9ai9-nodejs
  backstage.io/kubernetes-id: tafbn9ai9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tafbn9ai9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  